---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: niri-bluebuild
# description will be included in the image's metadata
description: This is my personal OS image, built for niri and ags(v2.3.0) based bar

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: 43 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  - type: dnf
    repos:
      files :
        - vscodium.repo
      copr:
        - lionheartp/Hyprland
        - alternateved/keyd
        - ublue-os/packages
        - avengemedia/danklinux
        - avengemedia/dms
        #VERY temporary
        - yalter/niri
      keys :
        - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
      cleanup: true
    install:
      install-weak-deps: false
      packages:
        #DMS experimental
        - dms
        - dms-greeter
        - cliphist
        - danksearch
        - matugen
        - ghostty
        - material-symbols-fonts
        - dgop
        #system functionnality
        - quickshell
        - keyd
        - NetworkManager
        - nm-connection-editor
        - bluez
        - tuned-ppd
        - niri
        - xwayland-satellite
        - brightnessctl
        - playerctl
        #- swww
        #- swaybg
        #- grim
        #- slurp
        - wl-clipboard
        #- wlsunset
        #- hypridle
        #- hyprlock
        #- mate-polkit
        - gamescope
        - fuzzel
        - ShellCheck
        - gnome-keyring
        - gstreamer1-plugins-good-qt6
        - kernel-tools
        - kf6-sonnet-hunspell
        - kio-extras
        - libproxy-bin
        - media-player-info
        - newt
        - nodejs-docs
        - nodejs-full-i18n
        - nodejs-npm
        - openssh-askpass
        - perl-NDBM_File
        - phonon-qt6-backend-vlc
        - python3-beaker
        - python3-crypto
        - python3-netifaces
        - python3-perf
        - python3-psutil
        - ripgrep
        - tree-sitter-cli
        - vlc-plugin-ffmpeg
        - vlc-plugin-pipewire
        - xdg-desktop-portal-gnome
        - xsel 
        - xset 
        - nmap-ncat
        - qalculate
        - fd-find
        - qt6ct
      #building dependencies
        - gcc
        - gcc-c++
        - pulseaudio-utils
        - cmake
        - meson
        - gobject-introspection-devel
        - gtk3-devel
        - gtk4-devel
        - gtk-layer-shell-devel
        - gtk4-layer-shell-devel
        - gobject-introspection-devel
        - wayland-protocols-devel
        - valadoc
        - vala
        - gdk-pixbuf2-devel
        - cairo-devel
        - cairo-gobject-devel
        - rust
        - cargo
        - pango-devel
        - graphene-devel
        - poppler-glib-devel
        - protobuf-compiler
        #- NetworkManager-libnm-devel
        - wireplumber-devel
        - pipewire-devel
        #Fonts, themes,etc 
        - adw-gtk3-theme
        - adwaita-fonts-all
        - fontawesome-6-free-fonts
        - gi-docgen-fonts
        #Language servers
        - nodejs-bash-language-server
        #Java
        - java-21-openjdk
        #CLI/apps not doable with flatpak or homebrew
        - bazaar
        - uupd
        - gucharmap
        - powertop
        - kde-connect
        - kde-connect-nautilus
        - qqc2-desktop-style
        - nautilus
        #- kitty
        - alacritty
        - neovim
        - nextcloud-client
        - nextcloud-client-nautilus
        - seahorse
        - epiphany
        - codium
#        - astal
#        - astal-gjs
#        - astal-gtk4
#        - astal-io
#        - astal-libs
#        - aylurs-gtk-shell2
      exclude :
        - waybar
  - type: rpm-ostree
    remove:
      - vim-enhanced
      - firefox
      - firefox-langpacks

  - type: brew

  - type: default-flatpaks
    configurations :
      - notify: false # Send notification after install/uninstall is finished (true/false)
        scope: system
        install:
          - org.mozilla.firefox
          - com.github.tchx84.Flatseal
          - com.mattjakeman.ExtensionManager
          - org.gnome.Loupe
          - net.nokyan.Resources
          - org.gnome.Calculator
          - org.gnome.Papers
          - org.gnome.TextEditor
          - org.gnome.baobab
          - org.gnome.font-viewer
          - org.gnome.Showtime
          - org.gtk.Gtk3theme.adw-gtk3
          - org.gtk.Gtk3theme.adw-gtk3-dark
          #More personal stuff
          - io.github.milkshiift.GoofCord
          - net.ankiweb.Anki
          - org.gimp.GIMP
          - org.libreoffice.LibreOffice
          - io.github.ungoogled_software.ungoogled_chromium
  - type: systemd
    user:
      enabled:
        - dms.service
  - type: signing # this sets up the proper policy & signing files for signed images to work fully

