---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: niri-bluebuild
# description will be included in the image's metadata
description: This is my personal OS image, built for niri and ags(v2.3.0) based bar

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  - type: dnf
    repos:
      copr:
        - solopasha/hyprland
        - alternateved/keyd
        - ublue-os/packages
        - errornointernet/walker
      cleanup: true
    install:
      install-weak-deps: false
      packages:
        #system functionnality
        - sddm
        - keyd
        - NetworkManager
        - nm-connection-editor
        - bluez
        - tuned-ppd
        - niri
        - xwayland-satellite
        - brightnessctl
        - playerctl
        - swww
        - swaybg
        - grim
        - slurp
        - wl-clipboard
        - hypridle
        - hyprlock
        - mate-polkit
        - gamescope
        - fuzzel
        - walker
        - ShellCheck
        - gnome-keyring
        - gstreamer1-plugins-good-qt6
        - kernel-tools
        - kf6-sonnet-hunspell
        - kio-extras
        - libproxy-bin
        - media-player-info
        - newt
        - nodejs-docs
        - nodejs-full-i18n
        - nodejs-npm
        - openssh-askpass
        - perl-NDBM_File
        - phonon-qt6-backend-vlc
        - python3-beaker
        - python3-crypto
        - python3-netifaces
        - python3-perf
        - python3-psutil
        - ripgrep
        - tree-sitter-cli
        - vlc-plugin-ffmpeg
        - vlc-plugin-pipewire
        - xdg-desktop-portal-gnome
        - xsel 
        - xset 
        - nmap-ncat
        - qalculate
        - fd-find
      #building dependencies
        - gcc
        - gcc-c++
        - pulseaudio-utils
        - cmake
        - meson
        - gobject-introspection-devel
        - gtk3-devel
        - gtk4-devel
        - gtk-layer-shell-devel
        - gtk4-layer-shell-devel
        - gobject-introspection-devel
        - wayland-protocols-devel
        - valadoc
        - vala
        - gdk-pixbuf2-devel
        - cairo-devel
        #- NetworkManager-libnm-devel
        - wireplumber-devel
        - pipewire-devel
        #Fonts, themes,etc 
        - adw-gtk3-theme
        - adwaita-fonts-all
        - fontawesome-6-free-fonts
        - gi-docgen-fonts
        #Language servers
        - nodejs-bash-language-server
        #Java
        - java-21-openjdk
        #CLI/apps not doable with flatpak or homebrew
        - uupd
        - gucharmap
        - powertop
        - kde-connect
        - kde-connect-nautilus
        - nautilus
        - kitty
        - alacritty
        - powertop
        - neovim
        - nextcloud-client
        - nextcloud-client-nautilus
#        - astal
#        - astal-gjs
#        - astal-gtk4
#        - astal-io
#        - astal-libs
#        - aylurs-gtk-shell2
      exclude :
        - waybar
  - type: rpm-ostree
    remove:
      - vim-enhanced
      - firefox
      - firefox-langpacks

  - type: brew

  - type: default-flatpaks
    configurations :
      - notify: false # Send notification after install/uninstall is finished (true/false)
        scope: system
        install:
          - org.mozilla.firefox
          - com.github.tchx84.Flatseal
          - com.mattjakeman.ExtensionManager
          - org.gnome.Loupe
          - net.nokyan.Resources
          - org.gnome.Calculator
          - org.gnome.Papers
          - org.gnome.TextEditor
          - org.gnome.baobab
          - org.gnome.font-viewer
          - org.gnome.Showtime
          - org.gtk.Gtk3theme.adw-gtk3
          - org.gtk.Gtk3theme.adw-gtk3-dark
          #More personal stuff
          - io.github.milkshiift.GoofCord
          - net.ankiweb.Anki
          - org.gimp.GIMP
          - org.libreoffice.LibreOffice
          - io.github.ungoogled_software.ungoogled_chromium
          - com.vscodium.codium
  - type : chezmoi
    repository: "https://github.com/An-Eagle/dotfiles" # my dotfiles repo
    all-users: false # make users have to enable chezmoi manually
    file-conflict-policy: skip # override changed files with those from the repo
  - type: systemd
    # this example disables automatic flatpak updates and enables a custom service unit for all users
    system:
      enabled:
        - sddm.service
    user :
      enabled:
        - chezmoi-update.timer

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

