---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: niri-bluebuild
# description will be included in the image's metadata
description: This is my personal OS image, built for niri and ags(v2.3.0) based bar

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: 44 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: common.yml
  - from-file: fonts.yml
  - from-file: flatpak.yml
  
  
  - type: dnf
    repos:
      files :
        - vscodium.repo
      copr:
        - lionheartp/Hyprland
        #- alternateved/keyd
        - ublue-os/packages
        - avengemedia/danklinux
        - avengemedia/dms
        #Temporary
        - yalter/niri
      keys :
        - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
      cleanup: true
    install:
      install-weak-deps: true
      packages:
        #DMS/danklinux
        - dms
        - dms-greeter
        - danksearch
        - matugen
        - dgop
        - cava
        - ghostty
        
        #Ublue-os/packages
        - bazaar
        #Vscodium repo
        - codium
        
        #system functionnality
        - NetworkManager
        - cups-pk-helper
        - bluez
        - tuned-ppd

        #Desktop basics
        - niri
        - xwayland-satellite
        - cliphist
        - brightnessctl
        - playerctl
        - wl-clipboard
        - ddcutil
        
        #Input
        - fcitx5
        - fcitx5-gtk
        - fcitx5-gtk2
        - fcitx5-gtk3
        - fcitx5-gtk4
        - fcitx5-qt
        - fcitx5-qt5
        - fcitx5-qt6
        - fcitx5-configtool

        #Fonts, themes,etc 
        - adw-gtk3-theme
        - adwaita-fonts-all
        - gi-docgen-fonts
        - papirus-icon-theme
        #Java
        - java-25-openjdk
        #QT
        - qt6-qtdeclarative-devel

        #GO
        - gopls
        - delve
        #CLI/apps not doable with flatpak or homebrew
        - podman-compose
        - qt6ct
        - uupd
        - powertop
        - kde-connect
        - fuse-sshfs
        - kde-connect-nautilus
        - nautilus
        - neovim
        - nextcloud-client
        - nextcloud-client-nautilus
        - tuned-gtk
        - ethtool
        - acpica-tools
        - v4l-utils

        #Lazy vim 
        - fd-find
        - curl 
        - ripgrep
        - tree-sitter-cli
        - neovim
        - fzf
        - gcc-c++ 
        - make 
        - findutils
        - python3-pip
        - nodejs
        - luarocks
        - golang
        - cargo
        - compat-lua
        - compat-lua-devel
        - ImageMagick
        - ghostscript
        - fish
      exclude :
        - waybar
        - alacritty
        
        
  - type: rpm-ostree
    remove:
      - vim-enhanced
      - firefox
      - firefox-langpacks


  - type: systemd
    system:
      enabled:
        - greetd.service
    user:
      enabled:
        - dms.service
  
