---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: niri-bluebuild
# description will be included in the image's metadata
description: This is my personal OS image, built for niri and ags(v2.3.0) based bar

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  - type: dnf
    repos:
      copr:
        - solopasha/hyprland
        - alternateved/keyd
        - ublue-os/staging
      cleanup: true
    install:
      packages:
        - sddm
        - keyd
        - niri
        - adw-gtk3-theme
        - adwaita-fonts-all
        - gcc
        - gcc-c++
        - hypridle
        - hyprlock
        - kde-connect
        - mate-polkit
        - nautilus
        - wlogout
        - xwayland-satellite
        - tuned-ppd
        - kitty
        - swww
        - bazaar
        - swaybg
        - gtk3-devel
        - gtk4-devel
        - gtk-layer-shell-devel
        - gtk4-layer-shell-devel
        - gobject-introspection-devel
        - wayland-protocols-devel
        - valadoc
        - vala
        - NetworkManager
        - NetworkManager-libnm-devel
        - network-manager-applet
        - bluez
        - blueman
        - wireplumber-devel
        - pipewire-devel
        - playerctl
        - pulseaudio-utils
        - brightnessctl
        - grim
        - slurp
        - wl-clipboard
        - cmake
        - meson
        - gobject-introspection-devel
        - gucharmap
#        - astal
#        - astal-gjs
#        - astal-gtk4
#        - astal-io
#        - astal-libs
#        - aylurs-gtk-shell2
#        - dunst
#        - nwg-look
#        - cliphist

  - type: brew

  - type: default-flatpaks
    configurations :
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        install:
          - org.mozilla.firefox
          - com.github.tchx84.Flatseal
          - com.mattjakeman.ExtensionManager
          - com.discordapp.Discord
          - org.gnome.Loupe
          - net.nokyan.Resources
          - org.gnome.Calculator
          - org.gnome.Papers
          - org.gnome.TextEditor
          - org.gnome.baobab
          - org.gnome.font-viewer
          - org.gtk.Gtk3theme.adw-gtk3
          - org.gtk.Gtk3theme.adw-gtk3-dark

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

