---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: niri-bluebuild
# description will be included in the image's metadata
description: This is my personal OS image, built for niri and ags(v2.3.0) based bar

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: 43 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  - type: dnf
    repos:
      files :
        - vscodium.repo
      copr:
        - lionheartp/Hyprland
        #- alternateved/keyd
        - ublue-os/packages
        - avengemedia/danklinux
        - avengemedia/dms-git
      keys :
        - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
      cleanup: true
    install:
      install-weak-deps: false
      packages:
        #DMS 
        - dms
        - dms-greeter
        - cliphist
        - danksearch
        - matugen
        - ghostty
        - dgop
        #system functionnality
        - quickshell
        #- keyd
        - NetworkManager
        #- nm-connection-editor
        - bluez
        - tuned-ppd
        - niri
        - xwayland-satellite
        - brightnessctl
        - playerctl
        - wl-clipboard
        - ddcutil
        - gamescope
        - fuzzel
        - ShellCheck
        - gnome-keyring
        - gstreamer1-plugins-good-qt6
        - kernel-tools
        - kf6-sonnet-hunspell
        - kio-extras
        - libproxy-bin
        - media-player-info
        - newt
        - nodejs-docs
        - nodejs-full-i18n
        - nodejs-npm
        - openssh-askpass
        - perl-NDBM_File
        - phonon-qt6-backend-vlc
        - python3-beaker
        - python3-crypto
        - python3-netifaces
        - python3-perf
        - python3-psutil
        - ripgrep
        - tree-sitter-cli
        - vlc-plugin-ffmpeg
        - vlc-plugin-pipewire
        - xdg-desktop-portal-gnome
        - xsel 
        - xset 
        - nmap-ncat
        - fd-find
        - qt6ct
        #Fonts, themes,etc 
        - adw-gtk3-theme
        - adwaita-fonts-all
        - fontawesome-6-free-fonts
        - gi-docgen-fonts
        - papirus-icon-theme
        - material-symbols-fonts
        - google-noto-fonts-all
        #Java
        - java-21-openjdk
        #CLI/apps not doable with flatpak or homebrew
        - podman-compose
        - bazaar
        - uupd
        - gucharmap
        - powertop
        - kde-connect
        - fuse-sshfs
        - kde-connect-nautilus
        - qqc2-desktop-style
        - nautilus
        - alacritty
        - neovim
        - nextcloud-client
        - nextcloud-client-nautilus
        - epiphany
        - codium
        #Lazy vim 
        - fd-find
        - curl 
        - ripgrep
        - tree-sitter-cli
        - neovim
        - fzf
        - gcc-c++ 
        - make 
        - findutils
        - python3-pip
        - nodejs
        - luarocks
        - golang
        - cargo
        - compat-lua
        - compat-lua-devel
        - ImageMagick
        - ghostscript
        - fish
      exclude :
        - waybar
  - type: rpm-ostree
    remove:
      - vim-enhanced
      - firefox
      - firefox-langpacks

  - type: brew

  - type: default-flatpaks
    configurations :
      - notify: false # Send notification after install/uninstall is finished (true/false)
        scope: system
        install:
          - org.mozilla.firefox
          - com.github.tchx84.Flatseal
          - com.mattjakeman.ExtensionManager
          - org.gnome.Loupe
          - net.nokyan.Resources
          - org.gnome.Calculator
          - org.gnome.Papers
          - org.gnome.TextEditor
          - org.gnome.baobab
          - org.gnome.font-viewer
          - org.gnome.Showtime
          - org.gtk.Gtk3theme.adw-gtk3
          - org.gtk.Gtk3theme.adw-gtk3-dark
          #More personal stuff
          - net.ankiweb.Anki
          - org.gimp.GIMP
          - org.libreoffice.LibreOffice
  - type: systemd
    system:
      enabled:
        - greetd.service
    user:
      enabled:
        - dms.service
  - type: signing # this sets up the proper policy & signing files for signed images to work fully

